logging:
  path: D:\\tmp

server:
  servlet:
    jsp:
      init-parameters:
        development: true
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: root
#    password: test