# 服务端口配置
server:
  servlet:
    context-path: /

spring:
  # 当前使用的profile
  profiles:
    active: dev
# springmvc jsp目录配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # http 编码配置
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache/ehcache_es.xml

# Shiro
shiro:
  # 允许shiro管理session
  userNativeSessionManager: true
  sessionManager:
    # 禁用URL会话重写
    sessionIdUrlRewritingEnabled: false
