# 服务端口配置
server:
  port: 18088
  servlet:
    context-path: /

spring:
  # 当前使用的profile
  profiles:
    active: local
  # springmvc jsp目录配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  # http 编码配置
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache/ehcache_es.xml
  messages:
    basename: classpath:messages/messages,classpath:messages/ValidationMessages
